---
title: "Lathyrus ms2: Selection on reaction norms - exploratory analyses"
output:
  pdf_document:
    toc: yes
    toc_depth: 4
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Read data created with previous scripts, include=FALSE}
data_sel<-read.csv(
  "C:/Users/User/Dropbox/SU/Projects/lathyrus/lathyrus_ms1/data/clean/data_sel.csv",
                       header=T,sep="\t",dec=",") 
#Read data used in ms1 (Data where both FFD and n_fl are available - 2411 flowering events)
```

```{r load packages, include=FALSE}
library(knitr)
library(pander)
library(tidyverse)
library(ggthemes)
library(broom)
library(gridExtra)
library(lme4)
library(lmerTest)
library(MuMIn)
library(ggrepel)
library(car)
library(effects)
library(RColorBrewer)
library(MCMCglmm)
library(blme)
library(beepr)
```

```{r Define ggplot themes, include=FALSE}
my_theme <- function(){
  theme_base()+theme(plot.background=element_rect(fill="white", colour=NA))+
  theme(legend.position="none")+theme(text=element_text(family="serif"))+
  theme(plot.title = element_text(hjust =-0.06))
}
my_theme_legend <- function(){
  theme_base()+theme(plot.background=element_rect(fill="white", colour=NA))+
  theme(text=element_text(family="serif"))+
  theme(plot.title = element_text(hjust =-0.06))
}
```

```{r pander options, include=FALSE}
panderOptions('table.continues', '')
```

# Check how many years of data are there for each plant individual

```{r check how many years of data, echo=FALSE, fig.height=3.5, fig.width=5}
(yrs_data<-data_sel[c(1:3,20,42,171:172,183)]%>%
   group_by(id)%>%
   summarise(n_years = n())%>%
   group_by(n_years)%>%
   summarise(n_pls=n())%>%
   arrange(desc(n_years))%>%
   mutate(cum_n_pls=cumsum(n_pls)))

ggplot(yrs_data,aes(n_years,cum_n_pls))+geom_bar(stat="identity")+
  scale_x_continuous(breaks=seq(1,12,1))+
  geom_text(aes(label=cum_n_pls), vjust=-0.5,family="serif")+
  xlab("Number of years")+ylab("Cumulated number of plants")+my_theme()
```

If we use plants with 3 or more years of data --> 359 plant individuals

If we use plants with 4 or more years of data --> 243 plant individuals

If we use plants with 5 or more years of data --> 156 plant individuals

# Create subsets of data with plants with 3/4/5 or more years of data

```{r create subsets}
(data_3yrs<- select(data_sel,c(1:3,20,42,171:172,183))%>% # Select columns needed by now
  group_by(id)%>%
  mutate(n_years = n(),first_yr =  min(year))%>%
  filter(n_years>=3))
data_3yrs$id<-droplevels(data_3yrs$id)
length(levels(data_3yrs$id)) # 359 plant individuals

(data_4yrs<- select(data_sel,c(1:3,20,42,171:172,183))%>% # Select columns needed by now
  group_by(id)%>%
  mutate(n_years = n(),first_yr =  min(year))%>%
  filter(n_years>=4))
data_4yrs$id<-droplevels(data_4yrs$id)
length(levels(data_4yrs$id)) # 243 plant individuals

(data_5yrs<-select(data_sel,c(1:3,20,42,171:172,183))%>% # Select columns needed by now
  group_by(id)%>%
  mutate(n_years = n(),first_yr =  min(year))%>%
  filter(n_years>=5))
data_5yrs$id<-droplevels(data_5yrs$id)
length(levels(data_5yrs$id)) # 156 plant individuals
```

```{r save data, include=FALSE}
save(data_3yrs, file="data_3yrs1.RData")
save(data_4yrs, file="data_4yrs1.RData")
save(data_5yrs, file="data_5yrs1.RData")
```

