---
title: "Lathyrus ms2: selection on reaction norms for flowering time"
subtitle: "Variation in selection among years using BLUPs - brms models"
author : "Alicia Valdés"
output:
  pdf_document:
    toc: yes
    toc_depth: 4
  html_notebook:
    toc: yes
    toc_depth: '4'
    latex_engine: xelatex
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r load packages, include=FALSE}
library(tidyverse)
library(tidyr)
library(beepr)
library(ggthemes)
library(ggeffects)
library(glmmTMB)
library(knitr)
library(parallel)
library(brms)
library(bayesplot)
library(viridis)
library(cowplot)
```

```{r Define ggplot themes and stuff, include=FALSE}
my_theme <- function(){
  theme_base()+theme(plot.background=element_rect(fill="white", colour=NA))+
  theme(legend.position="none")+theme(text=element_text(family="serif"))+
  theme(plot.title = element_text(hjust =-0.06))
}
my_theme_legend <- function(){
  theme_base()+theme(plot.background=element_rect(fill="white", colour=NA))+
  theme(text=element_text(family="serif"))+
  theme(plot.title = element_text(hjust =-0.06))
}
```

```{r load models, include=FALSE}
# Load previously run models
load("output/model_without_measurement_error.RData")
load("output/model_measurement_error.RData")
```

# Read data

```{r}
datadef_BLUPs<-read.csv("data/datadef_BLUPs.csv") 
head(datadef_BLUPs)
```

# Models with brms

```{r}
my.cores <- detectCores()
```

Does selection on plasticity depend on temperature when considering also plant size?

Trying different distributions and models with and without zero-inflation

```{r eval=FALSE, include=FALSE}
# Models with zero-inflation and no measurement error
modelBLUP_2_3_brms<-brm(bf(round(intactseed)~slope*cmean_4+
                             cn_shoot_vol_mean_sqrt+(1|id),
                        zi~slope*cmean_4+
                             cn_shoot_vol_mean_sqrt+(1|id)),
                        family="zero_inflated_negbinomial",data=datadef_BLUPs,
                        warmup = 1000,iter = 4000,thin=2,chains=4,
                        inits = "random",seed = 12345,cores = my.cores)
# Model with zero-inflation and measurement error
modelBLUP_2_4_brms<-brm(bf(round(intactseed)~me(slope,slope_sd)*cmean_4+
                             cn_shoot_vol_mean_sqrt+(1|id),
                        zi~me(slope,slope_sd)*cmean_4+
                             cn_shoot_vol_mean_sqrt+(1|id))+set_mecor(FALSE),
                        family="zero_inflated_negbinomial",data=datadef_BLUPs,
                        warmup = 1000,iter = 5000,thin=2,chains=4,
                        inits = "random",seed = 12345,cores = my.cores,
                        control = list(adapt_delta = 0.99,max_treedepth = 15))
# By default, latent noise-free variables are assumed to be correlated. 
# To change that, add set_mecor(FALSE) to your model formula object 

# slope_sd is the standard deviation (measure of variability) 
# (not standard error!) of the slope BLUP
# slope is the mean (measure of central tendency) of the slope BLUP
# The mean and sd are calculated from all the posterior draws 
# (6000 in our case) using posterior_summary

# WARNINGS for model modelBLUP_2_4_brms (after 7 days running!):

# 3: There were 78 divergent transitions after warmup. See
# http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
# to find out why this is a problem and how to eliminate them. 
# 4: There were 1997 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth above 15. See
# http://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded 
# 5: Examine the pairs() plot to diagnose sampling problems
#  
# 6: The largest R-hat is 2.26, indicating chains have not mixed.
# Running the chains for more iterations may help. See
# http://mc-stan.org/misc/warnings.html#r-hat 
# 7: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
# Running the chains for more iterations may help. See
# http://mc-stan.org/misc/warnings.html#bulk-ess 
# 8: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
# Running the chains for more iterations may help. See
# http://mc-stan.org/misc/warnings.html#tail-ess 
```

### Model summary and predictions

```{r}
print(modelBLUP_2_3_brms,digits=3)
print(modelBLUP_2_4_brms,digits=3)
# WARNINGS:
# Warning messages:
# 1: Parts of the model have not converged (some Rhats are > 1.05). Be careful when analysing the results! We recommend running more iterations and/or setting stronger priors. 
# 2: There were 78 divergent transitions after warmup. Increasing adapt_delta above 0.99 may help. See http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
```



```{r include=FALSE}
sessionInfo()
```